import './globals.css'
import { Swanky_and_Moo_Moo } from 'next/font/google'

const swanky_and_moo_moo = Swanky_and_Moo_Moo(
  { 
    subsets: ['latin'] ,
    weight: ['400'],
})

import Nav from '@components/Nav';
import Footer from '@components/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en' className={swanky_and_moo_moo.className}>
        <body>
          <div className='flex flex-col'>
            <Nav/>
            <main className='app'>
              {children}
            </main>
            <Footer/>
          </div>
        </body>
    </html>
  )
}
